### ISSUE TITLE
Write the GS solver into a funtion

### ISSUE THREAD

**Issue by Shuaiche95** [YT9719/Multigrid_Project#3]
Please write the GS solver into a function and complete the residual calculation ASAP. 
Then we can start to test our program with a simple 1D homogeneous problem.

**Comment by Shuaiche95** [comment]
The function could be like the MATLAB style pseudo code shown on the [WiKi](https://en.wikipedia.org/wiki/Multigrid_method).

**Comment by YT9719** [comment]
Isn't it in a function?

**Comment by Shuaiche95** [comment]
Sorry, you don't have any notes, so I didn't read all your codes. Please add the GS function into _multigrid.h_ file.

**Comment by YT9719** [comment]
I'll get that done, Im also implementing a struct to return both the result vector and residual

**Comment by Shuaiche95** [comment]
Please comment on the issue if you solve the issue and close the issue. Thanks.
