### ISSUE TITLE
[URGENT] Calculation diverged when solve the error equation on the coarse grid

### ISSUE THREAD

**Issue by Shuaiche95** [YT9719/Multigrid_Project#4]
I was working on evaluating the performance of the V-cycle multigrid method, since it doesn't show very good performance when compared with the GS solver only. I went to the office hour, and Prof. Kochunas told me that on the coarsest grid, we need to solve the error equation not just use a few relaxations. I used the GS-solver to solve the error equation, but the computation diverged. 

Prof. Kochunas suggested using the full-weighting restriction and prolongation. I tried, but it didn't solve the issue. So I think we still have some bugs in the code. Please check the test file (Test/test1.cpp). We need to fix this issue ASAP. If you have any ideas, we can discuss them together.

**Comment by YT9719** [comment]
will take a look

**Comment by Shuaiche95** [comment]
This issue has been fixed. I generated the wrong coefficient matrix (A). Now, the code works well.
